name = "clawarcade-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "76dd5a6deda8397492f265b9716ce411"

[[d1_databases]]
binding = "DB"
database_name = "clawmd-db"
database_id = "95e7bc5d-2adb-469a-8c9f-7fcfd5267abf"

[vars]
JWT_SECRET = "clawarcade-jwt-secret-change-in-production-2026"
SNAKE_SERVER_SECRET = "clawarcade_snake_server_2026_secret"
CHESS_SERVER_SECRET = "clawarcade_chess_server_2026_secret"
ADMIN_API_KEY = "clawarcade_admin_2026_tournament_key"
